# Basic Information:
### Title:  ROS test of tiltrotor fails #14200 
### Issue status: Closed
### Author: julianoes
### Issue open time: Feb 21, 2020
### Fixed by: #14203
# Report
### Report author: julianoes
### Report Time: Feb 21, 2020
### Report Content:   
The ROS test of tiltrotor started failing in CI and this can also be reproduced locally:  
    
```bash     
 PX4_DOCKER_REPO=px4io/px4-dev-ros-melodic:2020-02-11 Tools/docker_run.sh bash        
DONT_RUN=1 make px4_sitl gazebo        
test/rostest_px4_run.sh mavros_posix_test_mission.test mission:=VTOL_mission_1 vehicle:=tiltrotor        
```  
What happens is that the tiltrotor does not actually seem to take off but only switches to in-air for about 1 second and then auto-disarms again. I have seen this manually in testing as well, especially with tailsitter.  
Test output:  
    
```bash     
 INFO  [ecl/EKF] 5188000: reset position to GPS        
INFO  [ecl/EKF] 5188000: reset velocity to GPS        
INFO  [ecl/EKF] 5188000: commencing GPS fusion        
[ INFO] [1582276040.013415824, 17.360000000]: WP: mission received        
[ INFO] [1582276040.660517600, 18.004000000]: WP: mission sended        
[ WARN] [1582276041.664164514, 19.012000000]: CMD: Unexpected command 176, result 0        
[ INFO] [1582276042.674148856, 20.020000000]: FCU: ARMED by Arm/Disarm component command        
[ INFO] [1582276042.726149218, 20.072000000]: FCU: Takeoff to 15.0 meters above home.        
INFO  [commander] Takeoff detected        
[ INFO] [1582276049.615119419, 26.948000000]: FCU: Takeoff detected        
INFO  [commander] Landing detected        
[ INFO] [1582276050.309446351, 27.640000000]: FCU: Landing detected        
[ INFO] [1582276050.421811711, 27.752000000]: FCU: DISARMED by Auto disarm initiated        
INFO  [logger] closed logfile, bytes written: 2344626        
PX4 Exiting...        
Shutting down        
[Testcase: testVTOL_mission_1] ... ok        
[ROSTEST]-----------------------------------------------------------------------        
[px4.rosunit-VTOL_mission_1/test_mission][FAILURE]------------------------------        
position not reached | lat: 47.397736151, lon: 8.547064163, alt: 503.05, current pos_xy_d: 110.65, current pos_z_d: 14.77, best pos_xy_d: 110.47, best pos_z_d: 14.24, index: 0 | timeout(seconds): 60        
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run        
    testMethod()        
  File "/home/julianoes/src/Firmware/integrationtests/python_src/px4_it/mavros/mission_test.py", line 271, in test_mission        
    index)        
  File "/home/julianoes/src/Firmware/integrationtests/python_src/px4_it/mavros/mission_test.py", line 228, in reach_position        
    best_pos_z_d, index, timeout))        
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue        
    raise self.failureException(msg)        
--------------------------------------------------------------------------------        
SUMMARY        
 * RESULT: FAIL        
 * TESTS: 1        
 * ERRORS: 0        
 * FAILURES: 1        
```  
https://logs.px4.io/plot_app?log=feba07e1-cd9d-4ee6-8f77-f570f2ebc8fb  

# Comment
## Comment1
### Comment author: julianoes
### Comment Time: Feb 21, 2020
### Comment Content:   
It looks like this commit caused the regression:    
fc9d31c  

## Comment2
### Comment author: julianoes
### Comment Time: Feb 21, 2020
### Comment Content:   
What I said above might have been wrong. It seems to be the multicopter land detector detecting landed quickly after arming.  
